version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "senhaFoda123!"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  app:
    build: .
    environment:
      ConnectionStrings__ConexaoPadrao: "Server=sqlserver;Database=tarefa;User ID=sa;Password=senhaFoda123!;TrustServerCertificate=True;"

volumes:
  sql_data:
    driver: local
